# Generated by Django 4.0.5 on 2022-06-20 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('temporada', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Assistir', 'Assistir'), ('Assistido', 'Assistido'), ('Assistindo', 'Assistindo')], max_length=10)),
                ('comentarios', models.TextField(blank=True, verbose_name='Comentários')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
