# Generated by Django 4.0.5 on 2022-06-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='comentarios',
            field=models.TextField(blank=True, max_length=50, verbose_name='Comentários'),
        ),
    ]
